### ISSUE TITLE
Enable 2.8V mode

### ISSUE THREAD

**Issue by michael-p** [braincore/vl53l1x-rs#1]
Hi, thanks for writing and open-sourcing this binding!

Is there a way to activate the 2.8V mode for the Vl53l1x? It seems that by default the sensor operates in 1.8V mode and has to be switched by compiling the ST-drivers with the `USE_I2C_2V8` preprocessor macro defined (see [driver user manual](https://www.st.com/content/ccc/resource/technical/document/user_manual/group0/98/0d/38/38/5d/84/49/1f/DM00474730/files/DM00474730.pdf/jcr:content/translations/en.DM00474730.pdf) section 2.5.9, although it says `USE_I2C_2V8k` there which seems to be wrong...).

This is also done e.g. in the [Pololu implementation](https://github.com/pololu/vl53l1x-st-api-arduino/blob/master/vl53l1x-st-api/vl53l1_api.c#L757) and probably makes sense as a default since most existing breakout boards assume that the sensor is used with 2.8 Volts.

Maybe this could be done using a Cargo feature and then passed on in `build.rs` to the Makefile?

Thanks!
Michael

**Comment by braincore** [comment]
I haven't experimented with 2.8V mode. If you're willing to do some work, the strategy you've outlined is on the right track. Roughly:

1. Sanity check: adjust the `Makefile` to set the `USE_I2C_2V8` macro. That's the `-D` flag for gcc.
2. `cargo build` and test whether the newly compiled library works as expected.
3. If it all works, add a cargo feature and thread it through `build.rs` to the `Makefile`.

Let me know if you have any questions. I'm not great at Makefiles either :)

**Comment by michael-p** [comment]
I'll send in a PR in the following days. Interestingly it seems that defining `USE_I2C_2V8` is actually not necessary when running the sensor at 2.8V (even 3.3V in my case).

**Comment by braincore** [comment]
Interesting. Looks like I also overlooked the need to set the macro as I've been running at 3.3V. Since I'm not actively using the vl53lx right now, it'll be a while before I look into it.
